/**
 * Renders Chrome Web Store / AMO listing screenshots for HDRezka Speeds.
 *
 * Produces:
 *   01-hdrezka-panel.png       — full mock HDRezka video page with the panel
 *   02-hdrezka-panel-close.png — tight crop of the panel + player neighbourhood
 *   03-hdrezka-settings.png    — same page with the settings modal open
 *   04-welcome-page.png        — extension's actual welcome.html
 *
 * All shots are 1280x800 (CWS recommended).
 *
 * Why a mock page rather than a live rezka.ag visit:
 *   - Living mirrors are reachable from very few headless setups (regional
 *     blocks, anti-bot, login walls). A mock page renders identically every
 *     run and can be regenerated by anyone who clones the repo.
 *   - The mock uses VERBATIM CSS from src/ui/styles.ts (copy-pasted into the
 *     mock HTML), so the panel reads exactly as the user sees it on a real
 *     installation. The only synthetic part is the player surface.
 *
 * The welcome page is rendered through the actual built extension (loaded
 * as an unpacked extension), so it renders with all live JS modules and
 * CSS. This is the same code the user sees on first install.
 */

import { chromium } from '@playwright/test';
import { mkdirSync, existsSync, readdirSync, unlinkSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(__dirname, '..', '..');
const OUT = resolve(REPO, 'dist-store-assets', 'screenshots');
const MOCK = resolve(__dirname, 'mock-page.html');
const EXT_DIR = resolve(REPO, '.output', 'chrome-mv3');

if (!existsSync(EXT_DIR)) {
  console.error(`Extension build missing: ${EXT_DIR}\nRun \`npm run build\` first.`);
  process.exit(1);
}

if (!existsSync(OUT)) {
  mkdirSync(OUT, { recursive: true });
} else {
  for (const f of readdirSync(OUT)) {
    if (f.endsWith('.png')) unlinkSync(join(OUT, f));
  }
  console.log(`cleaned ${OUT}`);
}

// Load the actual built extension so welcome.html resolves its module
// imports under the chrome-extension:// scheme. headless=false is required
// for extension loading (Chromium dropped extension support in headless
// mode by default; "new headless" works but is unstable across versions).
const userDataDir = resolve(__dirname, '.tmp-profile');
const ctx = await chromium.launchPersistentContext(userDataDir, {
  headless: false,
  args: [
    `--disable-extensions-except=${EXT_DIR}`,
    `--load-extension=${EXT_DIR}`,
    '--no-first-run',
    '--no-default-browser-check',
  ],
  viewport: { width: 1280, height: 800 },
  deviceScaleFactor: 2,
});

let n = 1;
async function shoot(page, name, opts = {}) {
  const file = join(OUT, `${String(n).padStart(2, '0')}-${name}.png`);
  await page.screenshot({ path: file, ...opts });
  console.log(`saved ${file}`);
  n++;
}

// 1. Mock HDRezka — panel only.
const page1 = await ctx.newPage();
await page1.setViewportSize({ width: 1280, height: 800 });
await page1.goto(pathToFileURL(MOCK).href, { waitUntil: 'load' });
await page1.waitForTimeout(400);
await shoot(page1, 'hdrezka-panel');

// 2. Tight crop around the panel + player chrome.
const rect = await page1.evaluate(() => {
  const panel = document.querySelector('.vs-panel');
  const player = document.querySelector('.b-player');
  if (!panel || !player) return null;
  const playerR = player.getBoundingClientRect();
  const panelR = panel.getBoundingClientRect();
  return {
    top: Math.max(0, playerR.top - 8),
    height: panelR.bottom - playerR.top + 16,
  };
});
if (rect) {
  await page1.screenshot({
    path: join(OUT, `${String(n).padStart(2, '0')}-hdrezka-panel-close.png`),
    clip: { x: 0, y: rect.top, width: 1280, height: Math.min(rect.height, 800 - rect.top) },
  });
  console.log(`saved hdrezka-panel-close.png (cropped)`);
  n++;
}

// 3. Mock HDRezka — settings modal open.
const page3 = await ctx.newPage();
await page3.setViewportSize({ width: 1280, height: 800 });
await page3.goto(pathToFileURL(MOCK).href + '?modal=1', { waitUntil: 'load' });
await page3.waitForTimeout(600);
await shoot(page3, 'hdrezka-settings');

// 4. Welcome — through the built extension. Discover its ID via the service
// worker URL, then navigate to chrome-extension://<id>/welcome.html.
let extId = null;
// Wait a beat for the extension to register its service worker.
for (let i = 0; i < 30 && !extId; i++) {
  const sw = ctx.serviceWorkers().find((w) => w.url().startsWith('chrome-extension://'));
  if (sw) {
    extId = new URL(sw.url()).host;
    break;
  }
  await new Promise((r) => setTimeout(r, 200));
}

if (extId) {
  const page4 = await ctx.newPage();
  await page4.setViewportSize({ width: 1280, height: 800 });
  await page4.emulateMedia({ colorScheme: 'light' });
  await page4.goto(`chrome-extension://${extId}/welcome.html`, { waitUntil: 'networkidle' });
  // Welcome runs a layout pass + draws SVG connectors via requestAnimationFrame.
  await page4.waitForTimeout(1500);
  await shoot(page4, 'welcome-page');
} else {
  console.warn('welcome-page skipped: extension service worker not found');
}

await ctx.close();

// Best-effort cleanup of the temp profile so re-runs start fresh.
try {
  const { rmSync } = await import('node:fs');
  rmSync(userDataDir, { recursive: true, force: true });
} catch { /* swallow */ }

console.log(`\nAll screenshots in ${OUT}`);
